fabian-Okafor.md
=> Fabian.okafor

2018/spring/Sterne-MW@11am/vu-chule.md
=> Added markdown

2018/spring/Sterne-MW@11am/kalia_barkai.md
Kalia's short biography .md file
=> Kalia_Biography

2018/spring/Sterne-MW@11am/hueyning-lok.md
My bio for CS162 pre-class work.
=> Ning's bio

branch1/patrick-mutuku.md
Please accept my contribution to this project. There is a single file contained in this branch which contains my biography. Thanks.
=> Addition of Patrick's Biography 

2018/spring/Sterne-MW@11am/valyo-yolovski.md
Added bio as a requirement for the Pre-Class Work.
=> Created bio markdown file

2018/spring/Sterne-MW@11am/bio.md
=> Added zach bio

2018/spring/Sterne-MW@11am/patrick-m.md, 2018/spring/Sterne-MW@11am/patrick-mutuku.md
=> Add patrick's bio updated

2018/spring/Sterne-MW@3pm/nikesh-shrestha.md
=> Wrote my awesome biography

2018/spring/Sterne-MW@3pm/long-le.md
=> First pull req: my bio

2018/spring/Sterne-MW@3pm/zhanchen-guo.md
=> zhanchen guo bibliography

2018/spring/Sterne-MW@11am/zach_witzel.md
=> Changed zach bio name to fit naming conventions

barbara-favadacosta.md
Deleted barbara's bio from root folder
=> Deleted barbara-favadacosta.md

2018/spring/Sterne-MW@11am/namrata-haribal.md
This is my pre-class work from 2.1. Please approve my added biography.
=> Added my biography

2019/spring/Sterne-TT@9am/jason-liang.md
=> Jason Liang markdown

Hoang-Tran
=> Hoang - Tran 

Darya-Dyachkova.md, darya-dyachkova
=> Darya dyachkova

2019/spring/Sterne-TT@11am/yuhao-chen.md
=> Yuhao's Preclass Work

2019/spring/Sterne-TT@11am/isaac-schaal.md
=> Added Isaac-schaal Message

2019/spring/Sterne-TT@11am/abdul-qadir.md, abdul-qadir.md
=> preclass work

2019/spring/Sterne-TT@9am/jose-alvarez.md
It was fun to do though. This class really had great content. I enjoyed the readings, I ~may~ *(definitely)* come back to them later 💯 
🐶 😎 🤣
=> Pull request of A week later for make-up work, but created jose-alvarez

2020/spring/Sterne-MW@9am/Minh-Nguyen.md, 2020/spring/Sterne-MW@9am/Test.md
=> Minh-Nguyen.md

2020/spring/Sterne-MW@9am/ara-mkhoyan.md
=> Ara mkhoyan

2020/spring/Sterne-MW@9am/hiba-eloirghi.md
=> Create hiba-eloirghi.md, again.

2020/spring/Sterne-MW@9am/wei-ting-yap.md
@danyalnaeem please help review! Looks like the previously approved version was syntactically wrong
=> Corrected md syntax for wei-ting-yap.md

2020/spring/Sterne-MW@9am/hiba-eloirghi.md
Created a new one in our class's file
=> Create hiba-eloirghi.md in the correct file

2020/spring/Sterne-MW@11am/Taha-Bouhoun.md
=> Taha bouhoun

2020/spring/Sterne-MW@11am/bani-singh.md
Included whimsical biography and markdown experimentation
=> Bani's commit for preclass work

2020/spring/Sterne-MW@11am/nour-elkhalawy.md
adding my bio nour-elkhalawy.md to the master repo
=> Nour elkhalawy

2021/spring/Sterne-MW@11/austin-perzben.md
This is the pre-class work for Session 3 for Austin Perzben / Agustín Pérez del Castillo.
=> Session 3 pre-class work - Austin Perzben

2021/spring/Sterne-MW@11/Tiago-Flora.md
Adding my biography for session 2.1.
=> First version of T.F. biography

2021/spring/Sterne-MW@11/l-xia.md
=> Add l-xia.md

2021/spring/Sterne-MW@11/jackie-trang.md
able to push after having access
=> jackie intro 

2021/spring/Sterne-MW@11/dennis-kageni.md
=> Dennis kageni

2021/spring/Sterne-MW@11/akmarzhan-abylay.md
=> Akmarzhan Abylay

2021/spring/Sterne-MW@11/svitlana-midianko.md, svitlana-midianko.md
=> Svitlana midianko

2021/spring/Sterne-MW@11/batsal-ghimire.md
=> Batsal Intro

2021/spring/Sterne-TTh@21/Shukai-Ni.md
`Shukai-Ni.md` was created in `2021/spring/Sterne-TTh@21`
=> Add Shukai's bio

2021/spring/Sterne-TTh@21/nina-hamidli.md
Session 3 PCW: whimsical biography of myself
=> Initial commit: Nina's bio

2021/spring/Sterne-TTh@21/khanh-nguyen.md
Update the markdown to display the meme.
Source: https://guides.github.com/features/mastering-markdown/
Correct syntax should be like this:
`![GitHub Logo](/images/logo.png)`
`Format: ![Alt Text](url)`
Preview of the changes
=> Update khanh-nguyen.md to display the meme

2021/fall/Sterne-TTh@10/intro.md
Added intro.md to appropriate subdirectory
=> Chretien - Completion of CS162 2.1 PCW 

2021/fall/Sterne-TTh@10/biography.md
=> Add biography file for Evgeniia Buzulukova

2021/fall/Sterne-TTh@10/kalyane-bezerra.md
I am just following the guidelines from the pcw! Hope it is right!
=> Add biography

2021/fall/Sterne-TTh@10/pablo-guarneros.md
Created pablo-guarneros brief introduction.
@nazaryaremko I would love if you could propose some edits on the quote used in the heading.
=> Added Pablo Guarneros introduction

2021/fall/Sterne-TTh@10/aniket-das.md
=> Aniket das

2021/fall/Sterne-TTh@10/atahan-ozturk.md
=> Created atahan-ozturk.md

2021/fall/Sterne-TTh@10/chika-jinanwa.md
=> Initial commit for PCW 2.1

2021/fall/Sterne-TTh@10/yutaro-shimizu.md
Hello,
I just added and pushed my bio. Could your merge my branch to master? Thank you.
Best,
Yutaro
=> add Yutaro Shimizu's bio

2021/fall/Sterne-TTh@10/yuehhan-huang.md
Hi - I created a new markdown file in the repo. Can you take a look?
=> Yuehan's commit 

2022/spring/Sterne-MW@1pm/pierre-alkubeh.md
=> Pierre PCW

2022/spring/Sterne-MW@1pm/sona-vardanyan.md
After pushing, it showed me the file was empty, so I added the text manually here.
=> I have added my biography.

2022/spring/Sterne-MW@5pm/cyrus-chuang.md
Adding the bio for the session 3 PCW
=> Adding bio

2022/spring/Sterne-MW@5pm/dzvinka-koman.md
Here is my first pull request to the CS162 repository. 
As instructed, I cloned the repository, created a new branch, created an MD file with a short auto-biography. Then, I staged the changes, committed them, and pushed to the remote.
=> adding Dzvinkas bio

2022/spring/Sterne-MW@5pm/finn-macken.md
=> Whimsical bio for Finn

2022/spring/Sterne-MW@5pm/philip-barven.md
=> First Commit

2022/spring/Sterne-MW@5pm/enjui-chang.md
=> Upload enjui-chang.md

2022/spring/Sterne-MW@1pm/paul-song.md
The name is Paul and I'm constantly tired. Hello and goodbye.
=> paul-song.md

2022/fall/Scheffler-TT@10am/chloe-robillard.md
Thank you so much Professor! :)
=> Session 2.1 - Pre-Class Work

2022/fall/Scheffler-TT@10am/krithik_ravindran_bio.md
Session 3 CS162 Preclass work-Markdown file with short biography
=> krithik-ravindran

2022/fall/Scheffler-TT@10am/fellipe-franco.md, 2022/fall/Scheffler-TT@10am/fellipe-franco.md.txt
=> Fellipe franco

2022/fall/Scheffler-TT@10am/polina-vishnevskaya.md
Wrote a mini autobiography for CS162 PCW.
=> Added Polina's biography.

2022/fall/Scheffler-TT@10am/takato-kan.md
=> takato-kan.md

2023/spring/Scheffler-MW@0230PM/hussenmohammed-ibrahim.md
Just a pull request for the first commit of the course :)
=> Initial commit (created a markdown file as a test)

2023/spring/Scheffler-MW@0230PM/Abdullah-Khurram.md
Small Markdown file containing my biography.
=> Created Abdullah-Khurram.md

2023/spring/Scheffler-MW@0230PM/aromaatieno.md
This contains a short introduction.
=> My initial commit (a short introduction)

2023/spring/Scheffler-MW@0230PM/waiyego-maina.md
This is a combination of random facts about myself.
=> Added an introduction for Waiyego Maina

2023/spring/Scheffler-MW@0230PM/praise-ogwuche.md
This is a PCW for session 3 CS162. I have created a whimsical bio for myself with different markdown formatting included.
=> praise-ogwuche's whimsical bio

2023/Fall/Sterne-MW@8am/Somto-Umeh.md
- Somto's changes for CS162 Session 3 PCW
=> [CS162 2.1 PCW] Somto's changes

2023/Fall/Sterne-MW@8am/ifeoluwakolopin-are.md
Making a PR for the pre-class work for Session 3
=> initial commit ife

2023/Fall/Sterne-MW@8am/cassandra-cruz.md
=> Updated my Markdown File to have my silly bio

2023/Fall/Sterne-MW@10am/khaled_ahmed.md
=> Khaled ahmed

2023/Fall/Sterne-MW@10am/edona-saliu.md
=> created edona-saliu readme

2022/fall/Hanna-MW10am/Rany-Hanna.md, 2023/Fall/Sterne-MW@10am/Rany_Hanna.md
=> Rany hanna

2024/spring/Sterne-MW@8am/chiffon-my-nguyen.md
Added Pre-class Work for Session 3. There might be conflicts between pull requests
=> Add bio for Chiffon (My) Nguyen 

2023/Fall/Sterne-MW@8am/Catherine-Jackson.md
request to add catherine-jackson biography to main
=> add catherine-jackson biography

2024/spring/Sterne-MW@8am/Tanya_bas.md
=> cs162 pre-class work

2024/spring/Sterne-MW@8am/macbeth-matibe.md
whimsical biography of macbeth matibe. Pcw-muw session 3.
=> session 3 pcw-muw

2024/fall/Scheffler-MW@11am/elbion-redenica.md
Submitting biography for Elbion
=> Elbion's MD commit

2024/fall/Scheffler-MW@11am/enes-akyuz.md
Hello everyone, 
Here is my bio, hope you guys enjoy, I put a lot of effort into it haha!
=> Pre-Class Enes Akyuz

2024/fall/Scheffler-MW@11am/Godson-Ajodo.md
- Added my introduction as a markdown file
- Introduction consists of my name, Major, experience, and my interests
=> Introduction

2024/fall/Scheffler-MW@11am/thu-than.md
This is my bio description for pre-class work session 3.
=> Thu Than - Bio - PCW Session 3

2024/fall/Scheffler-MW@11am/jonathan-shamwana.md
This PR adds a Markdown file containing a short bio for Jonathan. The file is in the appropriate year/semester/section directory as per the guidelines.
=> Add Markdown introduction for Jonathan

2024/fall/Sterne-TTh@9am/jeevan-bhatta.md
CS162 Session 3 PCW.
Added a Whimsical Readme file in a new branch and pushed it to the cs162-test repo.
=> Added a Readme file

2024/fall/Sterne-TTh@9am/alaa-abbas.md
***Alaa Abbas added his biography***
=> Alaa Abbas added his branch with a biography

2024/fall/Sterne-TTh@9am/dilnaz-uasheva.md
The biography was added with markdown elements.
=> Add whimsical biography for Dilnaz Uasheva

2024/fall/Sterne-TTh@9am/Jiyun-Kim.md, Jiyun-Kim.md
This pull request adds a new biography page for Jiyun Kim using markdown formatting
=> Adding biography for Jiyun Kim

2024/fall/Sterne-TTh@9am/wisdom-ifode.md
=> Added biography markdown file

2024/fall/Sterne-TTh@9am/saliqua-kiran.md, 2024/fall/Sterne-TTh@9am/saliqua.md
*Senior at Minerva University*  
*Majoring in Strategic Finance and Applied CS and AI*  
---
I'm Saliqua, a senior at **Minerva University**—a student who believes that **spreadsheets** and **neural networks** are the keys to unlocking the mysteries of the universe (or at least securing a future in *Strategic Finance*). When not *dabbling in deep learning* or *optimizing investment portfolios*, I can be found sipping *cold brew* while discussing the latest developments in *AI ethics*.
---
1. **AI Enthusiast**:   
Obsessed with training models to predict the future...of **stock markets**, of course.
2. **Finance Nerd**:  
*Thinks Monte Carlo simulations* sound like a fancy casino game but is too busy running them to care.
3. **Global Nomad**:  
In true Minerva spirit, I have called **7 …
=> added md file

2024/fall/Sterne-TTh@9am/ian-wafula.md
Added Ian Wafula Readme, CS162 student  Fall 2024
=> Ian wafula Biography

2024/fall/Sterne-TTh@9am/peiqi-tea.md
I feel like I'm doing this wrong lmao
=> add: Pei Qi's bio

2024/fall/Sterne-TTh@9am/flavia.iespa.md
This PR adds Fla's biography into the repo.
=> adds fla's biography

2025/spring/Sterne-TTh@12PM/daisuke-fujiwara.md
=> daisuke-fujiwara-bio-markdown

2025/spring/Sterne-TTh@12PM/minkuan-gu.md, 2025/spring/Sterne-TTh@12PM/rawan-khalifa.md
Add whimsical biography for min kuan
=> added intro page for minkuan

2025/spring/Sterne-TTh@12PM/elhassan-elboraey.md
=> Elhassan's introduction

2025/fall/Miaskowska-MW12pm
=> Miaskowska Bio

2025/fall/2025/fall/Subasic-TTh@3PM/rayyan-afzal.md, 2025/fall/Subasic_TTh@3PM/rayyan-afzal.md
Major: Data Science
Minor: Economics
I’m excited to be taking CS162 this semester! I enjoy exploring how data tells stories and how economics helps explain the world around us.
=> Rayyan Afzal
